language: node_js
notifications:
  email: false
node_js:
  - lts/*
install:
  - travis_retry npm install
test:
  - npm test
before_deploy:
  - npm run coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
